@MyFirstWebApiProject_HostAddress = http://localhost:5215
### Get All Products
GET {{MyFirstWebApiProject_HostAddress}}/api/products
Accept: application/json
###
### Get Product with ID 1
GET {{MyFirstWebApiProject_HostAddress}}/api/products/1
Accept: application/json
###
### Create a New Product
POST {{MyFirstWebApiProject_HostAddress}}/api/products
Content-Type: application/json
{
    "Name": "New Product",
    "Price": 39.99,
    "Category": "Books"
}
###
### Update Product with ID 1
PUT {{MyFirstWebApiProject_HostAddress}}/api/products/1
Content-Type: application/json
{
    "Id": 1,
    "Name": "Updated Product",
    "Price": 49.99,
    "Category": "Electronics"
}
###
### Delete Product with ID 1
DELETE {{MyFirstWebApiProject_HostAddress}}/api/products/1
###